/**
 * The derived columns cannot drift from the document (SPEC-007).
 *
 * Sealed criterion:
 *
 * > `bodyHtml`, `bodyText` and `readingMinutes` stored after a save exactly
 * > equal the values recomputed from `bodyJson` by `lib/content/render.ts`.
 *
 * ── What this is actually protecting against ───────────────────────────────
 * `bodyJson` is canonical (DEC-002); the other three are caches. A cache that
 * silently falls behind its source is the worst kind of defect on a reading
 * site, because nothing fails: the article page serves the PREVIOUS revision's
 * HTML while the search index and the "5 min read" badge describe the current
 * one, and the only symptom is a reader seeing an old paragraph. There is no
 * error, no log line, and no test that would notice unless it is this one.
 *
 * The criterion is therefore stated as a round trip and tested as one. Every
 * case below goes through the REAL save path — `saveDraftContent`, which is
 * what the Server Action calls — then reads the row back out of SQLite and
 * recomputes all three values from the stored `bodyJson`. Nothing is asserted
 * against a literal, because a literal would only prove that this test and the
 * renderer agree on one document.
 *
 * ── The invariant is stronger than it looks ────────────────────────────────
 * Two modules derive these values and they are deliberately different ones:
 * `lib/db/articles.ts` recomputes `bodyText`/`readingMinutes` on every write
 * via `lib/derive/reading.ts`, while `bodyHtml` is passed in, generated by
 * `lib/content/render.ts` from the closed schema. So the columns are written by
 * two different code paths on the same call, and this file is what proves those
 * two paths saw the same document.
 *
 * The subtle way that breaks: the save path stores the SANITISED document but
 * derives the HTML from the RAW one (or vice versa). The row is then internally
 * inconsistent from the very first save, and `deriveContent` returning both the
 * sanitised doc and its HTML together is the design that makes writing that bug
 * awkward. Several cases below use documents that sanitisation visibly changes,
 * so a mismatch shows up as a diff rather than as an equality that happens to
 * hold because nothing was removed.
 */

import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';

import { createTestDatabase, type TestDatabase } from '../helpers/db';
import { disconnectDb } from '../../lib/db/client';
import { createUser } from '../../lib/db/users';
import { createArticle, getArticleById } from '../../lib/db/articles';
import { deriveReading } from '../../lib/derive/reading';
import { deriveContent, renderHtml } from '../../lib/content/render';
import { parseHtmlToDoc, sanitizeDoc } from '../../lib/content/schema';
import {
  createDraftContent,
  publishDraft,
  saveDraftContent,
  unpublishDraft,
} from '../../lib/content/publish';

const AT = new Date('2026-07-01T08:00:00.000Z');

let db: TestDatabase;
let authorId = '';
let articleId = '';

beforeAll(async () => {
  db = await createTestDatabase();
  process.env.DATABASE_URL = db.url;
}, 120_000);

afterAll(async () => {
  await disconnectDb();
  await db.drop();
});

beforeEach(async () => {
  await db.client.$executeRawUnsafe('DELETE FROM "ArticleTag"');
  await db.client.$executeRawUnsafe('DELETE FROM "Tag"');
  await db.client.$executeRawUnsafe('DELETE FROM "Article"');
  await db.client.$executeRawUnsafe('DELETE FROM "User"');

  const author = await createUser({
    email: 'author@titan.local',
    passwordHash: 'x',
    handle: 'author',
    name: 'The Author',
    createdAt: AT,
  });
  authorId = author.id;

  const article = await createArticle({
    authorId,
    title: 'A draft',
    bodyJson: { type: 'doc', content: [{ type: 'paragraph' }] },
    bodyHtml: '<p></p>',
    now: AT,
  });
  articleId = article.id;
});

/**
 * THE assertion of this file.
 *
 * Reads the row back from SQLite — not from the value the save returned — and
 * recomputes all three derived values from the stored `bodyJson`. Reading the
 * return value instead would test the function's own arithmetic and skip the
 * part that can actually go wrong: what reached the database.
 */
async function expectRowConsistent(id: string) {
  const row = await getArticleById(id);
  expect(row).not.toBeNull();
  if (!row) return;

  const recomputed = deriveContent(row.bodyJson);

  expect(row.bodyHtml).toBe(recomputed.bodyHtml);
  expect(row.bodyText).toBe(recomputed.bodyText);
  expect(row.readingMinutes).toBe(recomputed.readingMinutes);

  // The stored document must already be closed. If it is not, the equalities
  // above could hold while `bodyJson` carries something the schema forbids —
  // consistent, and consistently wrong.
  expect(row.bodyJson).toEqual(sanitizeDoc(row.bodyJson));

  // And the two derivation routes must agree: `lib/db/articles.ts` computes
  // bodyText/readingMinutes through `lib/derive/reading.ts`, while bodyHtml
  // comes from `lib/content/render.ts`. This is the line that proves both saw
  // the same document.
  const viaReading = deriveReading(row.bodyJson);
  expect(row.bodyText).toBe(viaReading.bodyText);
  expect(row.readingMinutes).toBe(viaReading.readingMinutes);
}

/** Documents that exercise every node and mark the schema has. */
const DOCUMENTS: Array<[string, unknown]> = [
  ['an empty document', { type: 'doc', content: [] }],
  [
    'a single paragraph',
    { type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Hello.' }] }] },
  ],
  [
    'headings at both levels',
    {
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Section' }] },
        { type: 'heading', attrs: { level: 3 }, content: [{ type: 'text', text: 'Subsection' }] },
      ],
    },
  ],
  [
    'every mark, stacked',
    {
      type: 'doc',
      content: [
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'loud',
              marks: [
                { type: 'bold' },
                { type: 'italic' },
                { type: 'strike' },
                { type: 'link', attrs: { href: 'https://example.com', title: 'A link' } },
              ],
            },
            { type: 'text', text: ' and ' },
            { type: 'text', text: 'inline()', marks: [{ type: 'code' }] },
          ],
        },
      ],
    },
  ],
  [
    'a quote, a rule, a code block and both lists',
    {
      type: 'doc',
      content: [
        {
          type: 'blockquote',
          content: [{ type: 'paragraph', content: [{ type: 'text', text: 'A quotation.' }] }],
        },
        { type: 'horizontalRule' },
        {
          type: 'codeBlock',
          attrs: { language: 'ts' },
          content: [{ type: 'text', text: 'const x: number = 1;' }],
        },
        {
          type: 'bulletList',
          content: [
            { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'one' }] }] },
            { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'two' }] }] },
          ],
        },
        {
          type: 'orderedList',
          attrs: { start: 3 },
          content: [
            { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'three' }] }] },
          ],
        },
      ],
    },
  ],
  [
    'an image with a caption and a hard break',
    {
      type: 'doc',
      content: [
        { type: 'image', attrs: { src: '/uploads/inline/u1/a.webp', alt: 'A chart', title: 'Fig 1' } },
        {
          type: 'paragraph',
          content: [
            { type: 'text', text: 'before' },
            { type: 'hardBreak' },
            { type: 'text', text: 'after' },
          ],
        },
      ],
    },
  ],
  [
    'text that must be escaped',
    {
      type: 'doc',
      content: [
        {
          type: 'paragraph',
          content: [{ type: 'text', text: 'A & B < C > D "quoted" — and an emoji 🌱' }],
        },
      ],
    },
  ],
  [
    'a hostile document the sanitiser must visibly change',
    {
      type: 'doc',
      content: [
        { type: 'script', content: [{ type: 'text', text: 'alert(1)' }] },
        {
          type: 'image',
          attrs: { src: '/uploads/inline/u1/a.webp', alt: 'ok', onerror: 'alert(1)' },
        },
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'link text',
              marks: [{ type: 'link', attrs: { href: 'javascript:alert(1)' } }],
            },
          ],
        },
      ],
    },
  ],
  [
    'a long article, over the one-minute reading floor',
    {
      type: 'doc',
      content: Array.from({ length: 30 }, (_, i) => ({
        type: 'paragraph',
        content: [
          {
            type: 'text',
            text: `Paragraph ${i} of a piece long enough that the reading estimate is not simply the floor of one minute. `.repeat(
              3,
            ),
          },
        ],
      })),
    },
  ],
];

// ---------------------------------------------------------------------------

describe('SPEC-007 — the stored columns equal the recomputed ones', () => {
  it.each(DOCUMENTS)('holds after saving %s', async (_label, body) => {
    const result = await saveDraftContent(articleId, {
      title: 'A draft',
      bodyJson: body,
      version: 1,
    });
    expect(result.ok).toBe(true);
    await expectRowConsistent(articleId);
  });

  it.each(DOCUMENTS)('holds when %s is the FIRST save, at /editor/new', async (_label, body) => {
    // The create path writes the same four columns through a different
    // repository function (`createArticle`, not `updateArticle`). A consistency
    // guarantee proven only on the update path would leave every article's
    // first revision unverified — and for a draft that is written once and
    // published, that is the only revision there is.
    const result = await createDraftContent(authorId, { title: 'Brand new', bodyJson: body }, AT);
    expect(result.ok).toBe(true);
    if (!result.ok || !result.articleId) return;
    await expectRowConsistent(result.articleId);
  });

  it('holds across a sequence of saves, each carrying the previous version', async () => {
    // Drift is cumulative in the real failure: it appears on save N, not save
    // one. Walking the whole document list through one article, in order,
    // exercises the update path repeatedly against a row whose previous
    // contents differ every time.
    let version = 1;
    for (const [, body] of DOCUMENTS) {
      const result = await saveDraftContent(articleId, {
        title: 'A draft',
        bodyJson: body,
        version,
      });
      expect(result.ok).toBe(true);
      if (!result.ok) return;
      version = result.version;
      await expectRowConsistent(articleId);
    }
    expect(version).toBe(1 + DOCUMENTS.length);
  });

  it('holds after a publish and an unpublish', async () => {
    // Both transitions bump `version` and touch the row. Neither should
    // regenerate the body — but "should not" is exactly the kind of thing that
    // stops being true when someone adds a `bodyHtml` line to `publishArticle`.
    await saveDraftContent(articleId, {
      title: 'A draft',
      bodyJson: {
        type: 'doc',
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: 'A paragraph well over the fifty-character floor.' }],
          },
        ],
      },
      version: 1,
    });
    await expectRowConsistent(articleId);

    await publishDraft(articleId, { tags: ['craft'] }, AT);
    await expectRowConsistent(articleId);

    await unpublishDraft(articleId, AT);
    await expectRowConsistent(articleId);
  });

  it('holds for a document that arrived as pasted HTML', async () => {
    const doc = parseHtmlToDoc(
      '<h1>Pasted</h1><p>Some <b>bold</b> text with a <a href="https://example.com">link</a>.</p>' +
        '<script>alert(1)</script><ul><li>one</li><li>two</li></ul>',
    );

    const result = await saveDraftContent(articleId, {
      title: 'A draft',
      bodyJson: doc,
      version: 1,
    });
    expect(result.ok).toBe(true);
    await expectRowConsistent(articleId);
  });
});

describe('SPEC-007 — what the save stores is the sanitised document', () => {
  it('stores the closed document, not the one that was posted', async () => {
    const hostile = {
      type: 'doc',
      content: [
        { type: 'script', content: [{ type: 'text', text: 'alert(1)' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'survivor' }] },
      ],
    };

    await saveDraftContent(articleId, { title: 'A draft', bodyJson: hostile, version: 1 });

    const row = await getArticleById(articleId);
    // The stored document differs from the input — which is what makes the
    // consistency check above meaningful rather than vacuous. If the save
    // stored the raw document and rendered the sanitised one, this pair of
    // assertions is where it would show.
    expect(row?.bodyJson).not.toEqual(hostile);
    expect(row?.bodyJson).toEqual(sanitizeDoc(hostile));
    expect(row?.bodyHtml).toBe(renderHtml(hostile));
    expect(row?.bodyText).toBe('survivor');
  });

  it('is stable: re-saving an unchanged document produces identical columns', async () => {
    // Idempotence at the column level. Without it, an autosave firing on a
    // document nobody edited would rewrite `bodyHtml` to something slightly
    // different every 30 seconds — invisible, and enough to make any
    // byte-comparison downstream (a cache key, a diff, this criterion) useless.
    const body = {
      type: 'doc',
      content: [
        {
          type: 'paragraph',
          content: [
            { type: 'text', text: 'stable', marks: [{ type: 'italic' }, { type: 'bold' }] },
          ],
        },
      ],
    };

    const first = await saveDraftContent(articleId, { title: 'A draft', bodyJson: body, version: 1 });
    expect(first.ok).toBe(true);
    const afterFirst = await getArticleById(articleId);

    const second = await saveDraftContent(articleId, {
      title: 'A draft',
      bodyJson: afterFirst?.bodyJson,
      version: first.ok ? first.version : 0,
    });
    expect(second.ok).toBe(true);
    const afterSecond = await getArticleById(articleId);

    expect(afterSecond?.bodyJson).toEqual(afterFirst?.bodyJson);
    expect(afterSecond?.bodyHtml).toBe(afterFirst?.bodyHtml);
    expect(afterSecond?.bodyText).toBe(afterFirst?.bodyText);
  });

  it('orders stacked marks the same way regardless of how they arrived', async () => {
    // The reason `MARK_SPECS` carries a rank. Two clients sending the same
    // marks in different orders must produce the same `bodyHtml`, or the
    // byte-equality this criterion asks for holds only for documents written by
    // whichever client happened to write them.
    const forwards = {
      type: 'doc',
      content: [
        {
          type: 'paragraph',
          content: [
            { type: 'text', text: 'x', marks: [{ type: 'bold' }, { type: 'italic' }] },
          ],
        },
      ],
    };
    const backwards = {
      type: 'doc',
      content: [
        {
          type: 'paragraph',
          content: [
            { type: 'text', text: 'x', marks: [{ type: 'italic' }, { type: 'bold' }] },
          ],
        },
      ],
    };

    expect(renderHtml(forwards)).toBe(renderHtml(backwards));
    expect(renderHtml(forwards)).toBe('<p><strong><em>x</em></strong></p>');
  });

  it('never stores a readingMinutes below one', async () => {
    // `max(1, ceil(words / 238))` — a one-line article must not read
    // "0 min read", which looks like a bug to a reader and is wrong anyway.
    await saveDraftContent(articleId, {
      title: 'A draft',
      bodyJson: { type: 'doc', content: [] },
      version: 1,
    });
    const row = await getArticleById(articleId);
    expect(row?.readingMinutes).toBe(1);
    expect(row?.bodyText).toBe('');
    await expectRowConsistent(articleId);
  });
});
